<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \MageWorx\DynamicOptionsBase\Block\DynamicOptions $block */
?>
<script>
    require([
        'jquery',
        'dynamicOptions',
        'uiRegistry'
    ], function ($, dynamicOptions, registry) {
        var optionBase = registry.get('mageworxOptionBase');
        if (optionBase) {
            optionBase.addUpdater(
                5,
                dynamicOptions(<?= /* @noEscape */ $block->getJsonData();?>)
            );
        } else {
            var updaters = registry.get('mageworxOptionUpdaters');
            if (!updaters) {
                updaters = {};
            }
            updaters[5] = dynamicOptions(<?= /* @noEscape */ $block->getJsonData();?>);
            registry.set('mageworxOptionUpdaters', updaters);
        }
    });
</script>
<script type="text/x-magento-init">
   {
       "*": {
           "dynamicOptionMinValueValidationRule": {
               "config": <?= /* @noEscape */ $block->getJsonData();?>
           },
            "dynamicOptionMaxValueValidationRule": {
               "config": <?= /* @noEscape */ $block->getJsonData();?>
           },
            "dynamicOptionStepValidationRule": {
               "config": <?= /* @noEscape */ $block->getJsonData();?>
           }
       }
   }
</script>
