<?php
/**
 * Mageplaza
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Mageplaza.com license that is
 * available through the world-wide-web at this URL:
 * https://www.mageplaza.com/LICENSE.txt
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category    Mageplaza
 * @package     Mageplaza_SecurityPro
 * @copyright   Copyright (c) Mageplaza (https://www.mageplaza.com/)
 * @license     https://www.mageplaza.com/LICENSE.txt
 */

namespace Mageplaza\SecurityPro\Model\ResourceModel\ActionLogBackup;

use Exception;
use Magento\Backend\Helper\Data;
use Magento\Framework\Data\Collection\EntityFactoryInterface;
use Magento\Framework\Data\Collection\Filesystem;
use Magento\Framework\Filesystem\Io\File;

/**
 * Class Collection
 * @package Mageplaza\Security\Model\ResourceModel\LoginLog
 */
class Collection extends Filesystem
{
    /**
     * @var Data
     */
    protected $_backendHelper;

    /**
     * @var File
     */
    protected $_file;

    /**
     * Collection constructor.
     *
     * @param EntityFactoryInterface $entityFactory
     * @param Data $backendHelper
     * @param File $file
     *
     * @throws Exception
     */
    public function __construct(
        EntityFactoryInterface $entityFactory,
        Data $backendHelper,
        File $file
    ) {
        $this->_backendHelper = $backendHelper;
        $this->_file          = $file;

        parent::__construct($entityFactory);

        $this->setCollectRecursively(true);
        $this->_file->checkAndCreateFolder(BP . '/var/backup/mageplaza_security_action_log');
        $this->addTargetDir(BP . '/var/backup/mageplaza_security_action_log');
    }

    /**
     * @param string $filename
     *
     * @return array
     */
    protected function _generateRow($filename)
    {
        $row         = parent::_generateRow($filename); // TODO: Change the autogenerated stub
        $row['time'] = date('Y-m-d H:i:s', filemtime($filename));
        $row['href'] = $this->_backendHelper->getUrl(
            'mpsecurity/actionlogbackup/download',
            ['filename' => $row['basename']]
        );

        return $row;
    }

    /**
     * @param $field
     * @param $direction
     *
     * @return \Magento\Framework\Data\Collection
     */
    public function addOrder($field, $direction)
    {
        return $this->setOrder($field, $direction);
    }
}
