<section
    x-data="heroSlider()"
    x-init="init()"
    class="relative overflow-hidden"
>

    <!-- Slides -->
    <div
        class="flex transition-transform duration-700 ease-in-out"
        :style="`transform: translateX(-${active * 100}%);`"
    >

        <!-- Slide 1 -->
        <div class="w-full shrink-0">
            <picture>
                <source
                    media="(min-width:768px)"
                    srcset="/media/wysiwyg/highland-essentials-kilts-outfits-_accessories_jpg.png"
                >

                <img
                    src="/media/wysiwyg/highland-essentials-kilts-outfits-_accessories_jpg.png"
                    alt=""
                    fetchpriority="high"
                    itemprop="image"
                    class="w-full h-auto object-cover"
                    loading="eager"
                >
            </picture>
        </div>

        <!-- Slide 2 -->
        <div class="w-full shrink-0">
            <picture>
                <source
                    media="(min-width:768px)"
                    srcset="/media/wysiwyg/highland-essentials-kilts-outfits-_accessories_jpg.png"
                >

                <img
                    src="/media/wysiwyg/highland-essentials-kilts-outfits-_accessories_jpg.png"
                    alt=""
                    fetchpriority="high"
                    itemprop="image"
                    class="w-full h-auto object-cover"
                    loading="lazy"
                >
            </picture>
        </div>

        <!-- Slide 3 -->
        <div class="w-full shrink-0">
            <picture>
                <source
                    media="(min-width:768px)"
                    srcset="/media/wysiwyg/highland-essentials-kilts-outfits-_accessories_jpg.png"
                >

                <img
                    src="/media/wysiwyg/highland-essentials-kilts-outfits-_accessories_jpg.png"
                    alt=""
                    fetchpriority="high"
                    itemprop="image"
                    class="w-full h-auto object-cover"
                    loading="lazy"
                >
            </picture>
        </div>

    </div>

    <!-- Dots -->
    <div
        class="absolute bottom-6 left-1/2  -translate-x-1/2 flex gap-3"
    >
        <template x-for="(slide,index) in slides">

            <button
                @click="go(index)"
                class="w-3 h-3 rounded-full transition"
                :class="active===index
                    ? 'bg-primary inline-[calc(var(--spacing)*7)]'
                    : 'bg-white'"
            ></button>

        </template>
    </div>

</section>
    <script>
function heroSlider() {
    return {
        slides: [1,2,3],
        active: 0,
        timer: null,

        init() {
            this.start();
        },

        start() {
            this.timer = setInterval(() => {
                this.next();
            }, 9000);
        },

        next() {
            this.active = (this.active + 1) % this.slides.length;
        },

        go(index) {
            this.active = index;
            clearInterval(this.timer);
            this.start();
        }
    }
}
</script>