<?php
declare(strict_types=1);

use FriendsOfHyva\ReactCheckout\ViewModel\CspNonceProvider;
use Utility\ReactCheckout\ViewModel\CheckoutLayout;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var CspNonceProvider $cspNonceProvider */
/** @var CheckoutLayout $checkoutLayout */

$cspNonceProvider = $block->getData('csp_nonce_provider');
$checkoutLayout = $block->getData('checkout_layout');
$buildJsFile = 'Utility_ReactCheckout::js/react-checkout.js';
$layoutVariant = $checkoutLayout->getVariant();
?>
<script nonce="<?= $block->escapeHtmlAttr($cspNonceProvider->getNonce()) ?>">
    window.hyvaCheckoutConfig = window.hyvaCheckoutConfig || {};
    window.hyvaCheckoutConfig.layoutVariant = '<?= $block->escapeHtmlAttr($layoutVariant) ?>';
</script>
<script nonce="<?= $escaper->escapeHtml($cspNonceProvider->getNonce()) ?>">
(function() {
    let reactCheckoutScriptLoaded = false;
    function loadReactCartScript () {
        if (reactCheckoutScriptLoaded) { return; }
        reactCheckoutScriptLoaded = true;
        var scriptTag = 'script';
        var firstScript = document.getElementsByTagName(scriptTag)[0];
        var newScript = document.createElement(scriptTag);
        newScript.async = true;
        newScript.defer = true;
        newScript.src = '<?= $block->escapeUrl($block->getViewFileUrl($buildJsFile)); ?>';
        firstScript.parentNode.insertBefore(newScript, firstScript);
    }
    window.addEventListener('private-content-loaded', loadReactCartScript);
    if (document.readyState === 'complete' || document.readyState === 'interactive') {
        loadReactCartScript();
    } else {
        document.addEventListener('DOMContentLoaded', loadReactCartScript);
    }
})();
</script>
