<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \MageWorx\OptionBase\Block\Product\View\Options $block */
?>
<?php if (count($block->getOptions())) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "optionBase": {
                    "optionConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                    "systemConfig": <?= /* @noEscape */ $block->getSystemJsonConfig('frontend') ?>,
                    "productConfig": <?= /* @noEscape */ $block->getProductJsonConfig() ?>,
                    "localePriceFormat": <?= /* @noEscape */ $block->getLocalePriceFormat() ?>,
                    "productFinalPriceExclTax": <?= (float)$block->getProductFinalPrice(false) ?>,
                    "productRegularPriceExclTax": <?= (float)$block->getProductRegularPrice(false) ?>,
                    "productFinalPriceInclTax": <?= (float)$block->getProductFinalPrice(true) ?>,
                    "productRegularPriceInclTax": <?= (float)$block->getProductRegularPrice(true) ?>,
                    "priceDisplayMode": "<?= (int)$block->getPriceDisplayMode() ?>",
                    "catalogPriceContainsTax": "<?= (int)$block->getCatalogPriceContainsTax() ?>",
                    "extendedOptionsConfig": <?= /* @noEscape */ $block->getExtendedOptionsConfig() ?>
                }
            }
        }
    </script>
<?php endif; ?>
