<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_CheckoutCore
*/
?>
<?php
    /** @var \Magento\Backend\Block\Template $block */
    /** @var \Magento\Framework\Escaper $escaper */
    // @codingStandardsIgnoreFile

    $url = $block->getUrl(
        'adminhtml/system_config/edit/section/amasty_checkout',
        ['expand' => 'design/layout']
    );
?>

<div class="fields-comment message">
    <?=
        $escaper->escapeHtml(__(
            'Manage Checkout Fields configuration page will become deprecated with one of upcoming'
            . ' One Step Checkout releases. Its features will be merged with '
        ));
    ?>
    <a href="<?= $escaper->escapeUrl($url) ?>">Layout Management.</a>
</div>

<div class="fields-comment message">
    <?=
        $escaper->escapeHtml(__(
            'When disabling City, Country, State/Province, Zip/Postal Code, please keep in mind that shopping cart'
            . ' will also be affected since those attributes are used in estimations and calculations.'
        ));
    ?>
</div>
